### ISSUE TITLE
Issues with Butterknife

### ISSUE THREAD

**Issue by rajivenator** [danylovolokh/VideoPlayerManager#10]
Hi,
First of all a huge ton of thanks for getting this library out in the wild. I was looking for such a solution for months. 
I have ran in to a problem with butterknife.
When i included your library in my project the viewholder bindings give an error with Butterknife.
And when i remove your library from dependencies the Bindings work correctly

**Comment by danylovolokh** [comment]
Please be more specific. Post some code examples, send log files, screen shots, describe your environment, library versions.

**Comment by rajivenator** [comment]
Hi ,Apologies for jumping to conclusions.
The issue is not with your library.

Apologies once again
