### ISSUE TITLE
Gradle ?

### ISSUE THREAD

**Issue by tuanth89** [danylovolokh/VideoPlayerManager#2]
@Danylo2006 , thank for awesome library, perfect if pause/play when touch like facebook app.
Can you add this library to gradle ??
And, have a problem happens when i assign class VideoPlayerView to xml, the Android Studio IDE freeze and not do anything. i don't know why, i did something wrong ??

**Comment by Danylo2006** [comment]
Sorry for late response.
I'm currently working on polishing the library. Will push the update soon

**Comment by tuanth89** [comment]
i'll hope soon. Thanks

**Comment by danylovolokh** [comment]
Redme.md was updated and dependencies were added.
dependencies {
    compile 'com.github.danylovolokh:video-player-manager:0.1.0'
    compile 'com.github.danylovolokh:list-visibility-utils:0.1.0'
}

**Comment by danylovolokh** [comment]
fixed freezing of Android Studio in latest push. I will update the dependency soon. 
0.1.0 doesn't have this commit

**Comment by tuanth89** [comment]
wow! Thank for update. IDE worked.
