### ISSUE TITLE
setlooping()

### ISSUE THREAD

**Issue by dk314** [danylovolokh/VideoPlayerManager#27]
I want to use VideoPlayerView,but i can't use setlooping() method of MediaPlayerWrapper,could you fix that?Thanks a lot

**Comment by danielchristopher1** [comment]
+1

**Comment by danylovolokh** [comment]
setLooping doesn't work on some Samsung devices. This has nothing to do with the library :)

**Comment by Tijn1314** [comment]
+1

**Comment by pawankumar01** [comment]
+1

**Comment by danylovolokh** [comment]
Hi, "setLooping" doesn't work on at least Samsung devices. That's why I didn't open this method. Either way. It is easy to open it by yourself. Just include the project as module and do the changes.
