### ISSUE TITLE
How can video urls of youtube and vimeo can be played using this library.

### ISSUE THREAD

**Issue by manisha-jain-bs** [danylovolokh/VideoPlayerManager#29]
I am getting this error when I try to play a youtube video using this library. 

> java.lang.RuntimeException: java.io.IOException: setDataSource failed.
>                                                                                  at com.volokh.danylo.video_player_manager.ui.VideoPlayerView.setDataSource(VideoPlayerView.java:263)

I am passing the youtube url `www.youtube.com/embed/GYFDRoJtfGM?wmode=opaque&autoplay=1`
but it is not working then which url do I need to pass in order to get this working. I want to play videos from vimeo also as same issue is coming when I play vimeo videos also.

**Comment by danylovolokh** [comment]
Closing it as duplicate:
https://github.com/danylovolokh/VideoPlayerManager/issues/23
