### ISSUE TITLE
How to switch video to fullscreen？

### ISSUE THREAD

**Issue by liwshuo** [danylovolokh/VideoPlayerManager#3]
Your method is great。 I am wondering how to switch video to fullscreen， i have tried to use a move textureview to a new Container，but the video will playback for a little time。Do you have any idea？ thanks

**Comment by danylovolokh** [comment]
There is an option, but sorry, this is not the scope of the project. You can contact me via e-mail if you still need it.

**Comment by brucetoo** [comment]
I think  [ListVideoPlay] (https://github.com/brucetoo/ListVideoPlay) may be helpful,  Modify from this lib
