### ISSUE TITLE
when current playing item roll out to window how does let it playing at a small player view in the window's corner？

### ISSUE THREAD

**Issue by qq2653203** [danylovolokh/VideoPlayerManager#35]
like this... sorry for my poor english 
![c634e13df83f05f8c4d48c453036d62e](https://cloud.githubusercontent.com/assets/8454148/15346730/55a359ac-1ced-11e6-9e7c-7049cb324d30.jpg)

**Comment by brucetoo** [comment]
This is out of range of this lib, but i have a plan to achieve what you want, [Here](https://github.com/brucetoo/ListVideoPlay) already has basic support demo, just relayout the [mVideoFloatContainer](https://github.com/brucetoo/ListVideoPlay/blob/master/app/src/main/java/com/brucetoo/listvideoplay/demo/RecyclerViewFragment.java#L47) to the left-bottom of parent view

**Comment by qq2653203** [comment]
thx a lot.  i have already achieved it
