### ISSUE TITLE
ANR caused by videoPlayerManager

### ISSUE THREAD

**Issue by RockyLin** [danylovolokh/VideoPlayerManager#42]
I have a recyclerView of videos in an activity, when I start a another activity from this activity, the new one would become ANR.

**Comment by brucetoo** [comment]
This may be caused by MediaPlayer.prepare, and try to replace with [MediaPlayer. prepareAsync](https://github.com/brucetoo/ListVideoPlay/blob/master/app/src/main/java/com/brucetoo/listvideoplay/videomanage/ui/MediaPlayerWrapper.java#L100)

**Comment by pro-softs** [comment]
@RockyLin I am the same problem. Did u get any solution for this issue?

**Comment by RockyLin** [comment]
@pro-softs I've abandoned this lib and switched to [Toro](https://github.com/eneim/Toro)

**Comment by pro-softs** [comment]
@RockyLin thanks....i have done the same thing

**Comment by Sach16** [comment]
> @pro-softs I've abandoned this lib and switched to [Toro](https://github.com/eneim/Toro)

Thanks for posting the library here, Great help!
