### ISSUE TITLE
Is VideoPlayerManager work with ExoPlayer?

### ISSUE THREAD

**Issue by PiotrWpl** [danylovolokh/VideoPlayerManager#5]
Hi,

firstly, thank You for all the work You did! It's a really cool project.

But I have one question, is it compatibile with Google ExoPlayer -> https://github.com/google/ExoPlayer ?

Thanks,
Peter

**Comment by danylovolokh** [comment]
Well, internally it uses Android MediaPlayer.class and I didn't try to use ExoPlayer.
The API is very similar. Maybe different Messages for MessagesHandlerThread have to be created.

Feel free to modify the code and use ExoPlayer instead :)
