### ISSUE TITLE
Excuse me，How to achieve multiple video players together in listview

### ISSUE THREAD

**Issue by androidMVP** [danylovolokh/VideoPlayerManager#7]
How to achieve multiple video players together

**Comment by danylovolokh** [comment]
There is a SingleVideoPlayerManager.

To get what you need you have to implement "MultipleVideoPlayerManager" or something like this.
Currently the library doesn't provide functionality like that

**Comment by androidMVP** [comment]
Can you tell  some ideas to  implement "MultipleVideoPlayerManager" ?

**Comment by danylovolokh** [comment]
You need to modify playNewVideo method. Do not stop previous playback just start the new one
But you need to know that it will not be supported by all devices. 

On some devices you won't be able to even play 2 movies concurrently. So it's a hard task to manage

**Comment by androidMVP** [comment]
Thank you！
